/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from '../../../app/rabbit/rabbit.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from './rabbit.component.css.shim';
var renderType_RabbitComponent_Host:import0.RenderComponentType = (null as any);
class _View_RabbitComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _RabbitComponent_0_4:import3.RabbitComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_RabbitComponent_Host0,renderType_RabbitComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('app-rabbit',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_RabbitComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._RabbitComponent_0_4 = new import3.RabbitComponent();
    this._appEl_0.initComponent(this._RabbitComponent_0_4,[],compView_0);
    compView_0.create(this._RabbitComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.RabbitComponent) && (0 === requestNodeIndex))) { return this._RabbitComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._RabbitComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_RabbitComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_RabbitComponent_Host === (null as any))) { (renderType_RabbitComponent_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,[],{})); }
  return new _View_RabbitComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const RabbitComponentNgFactory:import9.ComponentFactory<import3.RabbitComponent> = new import9.ComponentFactory<import3.RabbitComponent>('app-rabbit',viewFactory_RabbitComponent_Host0,import3.RabbitComponent);
const styles_RabbitComponent:any[] = [import10.styles];
var renderType_RabbitComponent:import0.RenderComponentType = (null as any);
class _View_RabbitComponent0 extends import1.AppView<import3.RabbitComponent> {
  _el_0:any;
  _text_1:any;
  _text_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_RabbitComponent0,renderType_RabbitComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'p',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n  rabbit works!\n',(null as any));
    this._text_2 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this.init([],[
      this._el_0,
      this._text_1,
      this._text_2
    ]
    ,[],[]);
    return (null as any);
  }
}
export function viewFactory_RabbitComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.RabbitComponent> {
  if ((renderType_RabbitComponent === (null as any))) { (renderType_RabbitComponent = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.Emulated,styles_RabbitComponent,{})); }
  return new _View_RabbitComponent0(viewUtils,parentInjector,declarationEl);
}